config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  root to: "lists#index"
  get "/lists", to: "lists#index"
  get "/lists/new", to: "lists#new"
  get "/lists/:id", to: "lists#show", as: :list_show
  post "/lists", to: "lists#create", as: :list


  resources :lists, only: [] do
    resources :bookmarks, only: [:show, :new, :create, :destroy]

  end




  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie_id, presence: true
  validates :list_id, presence: true
  validates :movie, uniqueness: { scope: :list }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true
  validates :title, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:destroy]
  def show
  end

  def new
    # raise
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
    # @list =
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list_id = params[:list_id]
    @bookmark.save
    redirect_to list_show_path(params[:list_id])
  end

  def destroy
    @bookmark.destroy
    redirect_to list_show_path(params[:list_id])
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]

  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
    # @bookmark =
  end

def new
  @list = List.new
end

def create
  @list = List.new(list_params)
  @list.save
  redirect_to list_path(@list)
end


  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
<h2>new bookmark form</h2>
  <%= simple_form_for [@list, @bookmark], html: { class: 'form-horizontal' },wrapper: :horizontal_form do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.submit "Submit review", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/bookmarks/show.html.erb
<h2>book mark show dummy</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">

  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
      <h2 class="navbar-brand">Movie Watchlists <i class="fa-solid fa-film"></i></h2>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <%= link_to "Index", lists_path, :class => "nav-link active" %>
            <a class="nav-link" href="#">X</a>
            <a class="nav-link" href="#">X</a>
            <a class="nav-link disabled" aria-disabled="true">X</a>
          </div>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>


<%# class="nav-link active" aria-current="page" %>
  <%# <%= link_to 'Back', products_path, :class => "btn"%>
<%#  %>

app/views/lists/index.html.erb
<h1>index lists</h1>
<ul>
  <% @lists.each do |list| %>
    <li><%= link_to list.name, list_show_path(list.id) %></li>
  <% end %>

  <%= link_to "new list", lists_new_path %>
</ul>

app/views/lists/new.html.erb
<div class="container">
<h2>hi i'm new list page</h2>

  <%= simple_form_for @list, html: { class: 'form-horizontal' },wrapper: :horizontal_form do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>

    <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="container">

  <h1><%= @list.name %></h1>
  <% if @list.photo %>
  <%= cl_image_tag @list.photo.key, height: 300, width: 400, crop: :fill %>
  <% end %>



  <div class="row">
    <% @list.movies.each do |movie| %>
    <% bookmark = Bookmark.find_by(movie: movie, list: @list) %>
      <div class="col-4">
        <div class="card" style="width: 18rem;">
          <h3><%= movie.title %></h3>
          <img src=<%= movie.poster_url %> alt="movie poster">
          <div class="row">
            <div class="col-4">
              <p><%= bookmark.comment %></p>
            </div>
            <div class="col-4">
            </div>
            <div class="col-4">
              <%= link_to "delete this bookmark",
              list_bookmark_path(@list, bookmark),
              data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
              :class =>"btn btn-secondary" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

      <div class="col-6">

      <div class="crd">
        <h2>add another movie <i class="fa-solid fa-ticket"></i></h2>
        <%= simple_form_for [@list, @bookmark], html: { class: 'form-horizontal' },wrapper: :horizontal_form do |f| %>
          <%= f.input :comment %>
          <%= f.association :movie %>
          <%= f.submit "Submit", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>a
  </div>
</div>

<%# @list.id, @list.bookmarks.where(:movie_id == movie.id) %>
<%# list_bookmark_path(@list.bookmarks.where(movie_id: movie.id)), %>

<%# list_bookmark_path(@list.bookmarks.where(:movie_id == movie.id)) %>